import * as React from 'react';
import {
  ScrollView,
  View,
  StyleSheet,
  Text,
  TouchableOpacity,
  Image,
} from 'react-native';
import {vh, vw, normalize} from '../dimensions/dimension';

export default function TermsOfUse({navigation}) {
  return (
    <View style={styles.container}>
      <View style={styles.Header}>
        <TouchableOpacity
          style={styles.arrowView}
          onPress={() => navigation.goBack()}>
          <Image source={require('../assets/arrow.png')} style={styles.icon} />
        </TouchableOpacity>
        <View style={styles.viewProfile}>
          <Text style={styles.headerText}>Terms Of Use </Text>
        </View>
      </View>
      <View style={styles.subHeader}>
        <Text style={styles.text}>Terms Of Use</Text>
      </View>
      <ScrollView style={{margin: normalize(8), textAlign: 'justify'}}>
        <Text
          style={{
            color: 'white',
            fontSize: normalize(13),
            textAlign: 'justify',
          }}>
          Last updated: 29th March, 2019{'\n'} {'\n'} {'\n'} This document is an
          electronic record in terms of Information Technology Act, 2000 and
          rules there under as applicable and the amended provisions pertaining
          to electronic records in various statutes as amended by the
          Information Technology Act, 2000. {'\n'}
          {'\n'} {'\n'}
          This electronic record is generated by a computer system and does not
          require any physical or digital signatures. This is a legal and
          binding agreement between you, the user (“User” or “You”) of the
          Services, as defined below, and Contagious Online Media Network
          Private Limited (“TVF”) stating the terms that govern Your use of the
          Site or the Platform, as defined below. You have accepted these Terms
          of Use, which govern your use of our service. Personally identifying
          information is subject to our Privacy Policy, the terms of which are
          incorporated herein. Please review our Privacy Statement to understand
          our practices. {'\n'} {'\n'} {'\n'}
          <Text style={{fontWeight: 'bold'}}>
            {' '}
            ACCESSING THIS WEBSITE, YOU CONSENT, AGREE AND UNDERTAKE TO ABIDE,
            BE BOUND BY AND ADHERE TO THE TERMS OF USE ("Terms of Use" or
            "Terms" or "Terms and Conditions" AND IF YOU DO NOT AGREE TO THESE
            TERMS OF USE, YOU ARE NOT ENTITLED TO AVAIL OF / USE THE SERVICES
            AND ANY USE THEREAFTER SHALL BE UNAUTHORIZED.
          </Text>{' '}
          {'\n'} {'\n'} {'\n'}
          BY TVF provides a personalized subscription services that allows our
          members to access TVF Content streamed over internet. {'\n'} {'\n'}{' '}
          {'\n'}{' '}
          <Text
            style={{
              fontWeight: 'bold',
              fontSize: normalize(18),
            }}>
            1. Description of Service and Acceptance of the Terms of Uses
          </Text>
          {'\n'} {'\n'}
          Contagious Online Media Network Private Limited (TVF) ("TVF," "we," or
          "us") provides an online video service offering a selection of shows,
          movies, clips, and other content (collectively, the "Content"). Our
          video service, the Content, our player for viewing the Content (the
          "Video Player") and any other features, tools, materials, or other
          services (including third party branded services) offered from time to
          time by TVF through a variety of Access Points (defined below) are
          referred to collectively as the "Services." The term "Access Points"
          refers to, collectively, the https://tvfplay.com/ website (the
          "Site"), applications, and other places where any Services are
          available, including websites and applications of TVF's third party
          distribution partners and other websites where users or website
          operators are permitted to embed or have otherwise licensed the Video
          Player. {'\n'} {'\n'} The use of TVF Services is available only to
          persons who can form legally binding contracts under Indian Contract
          Act, 1872. Persons who are incompetent to contract within the meaning
          of the Indian Contract Act, 1872 are not eligible to use the Services.
          {'\n'} {'\n'}
          Please note that the availability of, and Your ability to access, the
          Content or some part of Services, (a) is subject to TVF's sole
          discretion and/or (b) may be dependent upon Your geographical location
          and/or (c) is on the condition that not all Content or Services will
          be available to all viewers. On account of the nature of the Internet,
          this Site and the Services may also be accessed in various
          geographical locations; and You hereby agree and acknowledge that You
          are accessing this Site and using the Services, at Your own risk,
          choice and initiative and You agree and undertake to ensure that Your
          use of the Site and the Services complies with all applicable laws
          including the local laws in Your jurisdiction. Further, such Services
          and Content may vary from place to place, time to time and device to
          device and are subject to various parameters such as specifications,
          device, Internet availability and speed, bandwidth, etc. To facilitate
          Your viewership and access, the Services can be packaged by TVF, at
          its sole discretion, through different models such as, Content or
          Services may be accessible (a) free of charge which may include
          advertisements or commercials or (b) via subscription through payment
          of a subscription fee or (c) a pay-per-view model with or without
          advertisements/commercials or (d) with a combination of the foregoing
          on the Site.{'\n'} {'\n'} Use of the Services (including access to the
          Content) is subject to compliance with these Terms and any end user
          license agreement that might accompany the applicable Service.
          Therefore, by visiting the TVF Site or using any of the Services
          through any other Access Point you are agreeing to these Terms.
          {'\n'} {'\n'} {'\n'}
          <Text
            style={{
              fontWeight: 'bold',
              fontSize: normalize(18),
            }}>
            2. Description of Service and Acceptance of the Terms of Uses
          </Text>
          {'\n'} {'\n'}
          Contagious Online Media Network Private Limited (TVF) ("TVF," "we," or
          "us") provides an online video service offering a selection of shows,
          movies, clips, and other content (collectively, the "Content"). Our
          video service, the Content, our player for viewing the Content (the
          "Video Player") and any other features, tools, materials, or other
          services (including third party branded services) offered from time to
          time by TVF through a variety of Access Points (defined below) are
          referred to collectively as the "Services." The term "Access Points"
          refers to, collectively, the https://tvfplay.com/ website (the
          "Site"), applications, and other places where any Services are
          available, including websites and applications of TVF's third party
          distribution partners and other websites where users or website
          operators are permitted to embed or have otherwise licensed the Video
          Player. {'\n'} {'\n'} The use of TVF Services is available only to
          persons who can form legally binding contracts under Indian Contract
          Act, 1872. Persons who are incompetent to contract within the meaning
          of the Indian Contract Act, 1872 are not eligible to use the Services.
          {'\n'} {'\n'}
          Please note that the availability of, and Your ability to access, the
          Content or some part of Services, (a) is subject to TVF's sole
          discretion and/or (b) may be dependent upon Your geographical location
          and/or (c) is on the condition that not all Content or Services will
          be available to all viewers. On account of the nature of the Internet,
          this Site and the Services may also be accessed in various
          geographical locations; and You hereby agree and acknowledge that You
          are accessing this Site and using the Services, at Your own risk,
          choice and initiative and You agree and undertake to ensure that Your
          use of the Site and the Services complies with all applicable laws
          including the local laws in Your jurisdiction. Further, such Services
          and Content may vary from place to place, time to time and device to
          device and are subject to various parameters such as specifications,
          device, Internet availability and speed, bandwidth, etc. To facilitate
          Your viewership and access, the Services can be packaged by TVF, at
          its sole discretion, through different models such as, Content or
          Services may be accessible (a) free of charge which may include
          advertisements or commercials or (b) via subscription through payment
          of a subscription fee or (c) a pay-per-view model with or without
          advertisements/commercials or (d) with a combination of the foregoing
          on the Site.{'\n'} {'\n'} Use of the Services (including access to the
          Content) is subject to compliance with these Terms and any end user
          license agreement that might accompany the applicable Service.
          Therefore, by visiting the TVF Site or using any of the Services
          through any other Access Point you are agreeing to these Terms.
          {'\n'} {'\n'} {'\n'}
          <Text
            style={{
              fontWeight: 'bold',
              fontSize: normalize(18),
            }}>
            3. Description of Service and Acceptance of the Terms of Uses
          </Text>
          {'\n'} {'\n'}
          Contagious Online Media Network Private Limited (TVF) ("TVF," "we," or
          "us") provides an online video service offering a selection of shows,
          movies, clips, and other content (collectively, the "Content"). Our
          video service, the Content, our player for viewing the Content (the
          "Video Player") and any other features, tools, materials, or other
          services (including third party branded services) offered from time to
          time by TVF through a variety of Access Points (defined below) are
          referred to collectively as the "Services." The term "Access Points"
          refers to, collectively, the https://tvfplay.com/ website (the
          "Site"), applications, and other places where any Services are
          available, including websites and applications of TVF's third party
          distribution partners and other websites where users or website
          operators are permitted to embed or have otherwise licensed the Video
          Player. {'\n'} {'\n'} The use of TVF Services is available only to
          persons who can form legally binding contracts under Indian Contract
          Act, 1872. Persons who are incompetent to contract within the meaning
          of the Indian Contract Act, 1872 are not eligible to use the Services.
          {'\n'} {'\n'}
          Please note that the availability of, and Your ability to access, the
          Content or some part of Services, (a) is subject to TVF's sole
          discretion and/or (b) may be dependent upon Your geographical location
          and/or (c) is on the condition that not all Content or Services will
          be available to all viewers. On account of the nature of the Internet,
          this Site and the Services may also be accessed in various
          geographical locations; and You hereby agree and acknowledge that You
          are accessing this Site and using the Services, at Your own risk,
          choice and initiative and You agree and undertake to ensure that Your
          use of the Site and the Services complies with all applicable laws
          including the local laws in Your jurisdiction. Further, such Services
          and Content may vary from place to place, time to time and device to
          device and are subject to various parameters such as specifications,
          device, Internet availability and speed, bandwidth, etc. To facilitate
          Your viewership and access, the Services can be packaged by TVF, at
          its sole discretion, through different models such as, Content or
          Services may be accessible (a) free of charge which may include
          advertisements or commercials or (b) via subscription through payment
          of a subscription fee or (c) a pay-per-view model with or without
          advertisements/commercials or (d) with a combination of the foregoing
          on the Site.{'\n'} {'\n'} Use of the Services (including access to the
          Content) is subject to compliance with these Terms and any end user
          license agreement that might accompany the applicable Service.
          Therefore, by visiting the TVF Site or using any of the Services
          through any other Access Point you are agreeing to these Terms.
          {'\n'} {'\n'} {'\n'}
          <Text
            style={{
              fontWeight: 'bold',
              fontSize: normalize(18),
            }}>
            4. Description of Service and Acceptance of the Terms of Uses
          </Text>
          {'\n'} {'\n'}
          Contagious Online Media Network Private Limited (TVF) ("TVF," "we," or
          "us") provides an online video service offering a selection of shows,
          movies, clips, and other content (collectively, the "Content"). Our
          video service, the Content, our player for viewing the Content (the
          "Video Player") and any other features, tools, materials, or other
          services (including third party branded services) offered from time to
          time by TVF through a variety of Access Points (defined below) are
          referred to collectively as the "Services." The term "Access Points"
          refers to, collectively, the https://tvfplay.com/ website (the
          "Site"), applications, and other places where any Services are
          available, including websites and applications of TVF's third party
          distribution partners and other websites where users or website
          operators are permitted to embed or have otherwise licensed the Video
          Player. {'\n'} {'\n'} The use of TVF Services is available only to
          persons who can form legally binding contracts under Indian Contract
          Act, 1872. Persons who are incompetent to contract within the meaning
          of the Indian Contract Act, 1872 are not eligible to use the Services.
          {'\n'} {'\n'}
          Please note that the availability of, and Your ability to access, the
          Content or some part of Services, (a) is subject to TVF's sole
          discretion and/or (b) may be dependent upon Your geographical location
          and/or (c) is on the condition that not all Content or Services will
          be available to all viewers. On account of the nature of the Internet,
          this Site and the Services may also be accessed in various
          geographical locations; and You hereby agree and acknowledge that You
          are accessing this Site and using the Services, at Your own risk,
          choice and initiative and You agree and undertake to ensure that Your
          use of the Site and the Services complies with all applicable laws
          including the local laws in Your jurisdiction. Further, such Services
          and Content may vary from place to place, time to time and device to
          device and are subject to various parameters such as specifications,
          device, Internet availability and speed, bandwidth, etc. To facilitate
          Your viewership and access, the Services can be packaged by TVF, at
          its sole discretion, through different models such as, Content or
          Services may be accessible (a) free of charge which may include
          advertisements or commercials or (b) via subscription through payment
          of a subscription fee or (c) a pay-per-view model with or without
          advertisements/commercials or (d) with a combination of the foregoing
          on the Site.{'\n'} {'\n'} Use of the Services (including access to the
          Content) is subject to compliance with these Terms and any end user
          license agreement that might accompany the applicable Service.
          Therefore, by visiting the TVF Site or using any of the Services
          through any other Access Point you are agreeing to these Terms.
          {'\n'} {'\n'} {'\n'}
          <Text
            style={{
              fontWeight: 'bold',
              fontSize: normalize(18),
            }}>
            5. Description of Service and Acceptance of the Terms of Uses
          </Text>
          {'\n'} {'\n'}
          Contagious Online Media Network Private Limited (TVF) ("TVF," "we," or
          "us") provides an online video service offering a selection of shows,
          movies, clips, and other content (collectively, the "Content"). Our
          video service, the Content, our player for viewing the Content (the
          "Video Player") and any other features, tools, materials, or other
          services (including third party branded services) offered from time to
          time by TVF through a variety of Access Points (defined below) are
          referred to collectively as the "Services." The term "Access Points"
          refers to, collectively, the https://tvfplay.com/ website (the
          "Site"), applications, and other places where any Services are
          available, including websites and applications of TVF's third party
          distribution partners and other websites where users or website
          operators are permitted to embed or have otherwise licensed the Video
          Player. {'\n'} {'\n'} The use of TVF Services is available only to
          persons who can form legally binding contracts under Indian Contract
          Act, 1872. Persons who are incompetent to contract within the meaning
          of the Indian Contract Act, 1872 are not eligible to use the Services.
          {'\n'} {'\n'}
          Please note that the availability of, and Your ability to access, the
          Content or some part of Services, (a) is subject to TVF's sole
          discretion and/or (b) may be dependent upon Your geographical location
          and/or (c) is on the condition that not all Content or Services will
          be available to all viewers. On account of the nature of the Internet,
          this Site and the Services may also be accessed in various
          geographical locations; and You hereby agree and acknowledge that You
          are accessing this Site and using the Services, at Your own risk,
          choice and initiative and You agree and undertake to ensure that Your
          use of the Site and the Services complies with all applicable laws
          including the local laws in Your jurisdiction. Further, such Services
          and Content may vary from place to place, time to time and device to
          device and are subject to various parameters such as specifications,
          device, Internet availability and speed, bandwidth, etc. To facilitate
          Your viewership and access, the Services can be packaged by TVF, at
          its sole discretion, through different models such as, Content or
          Services may be accessible (a) free of charge which may include
          advertisements or commercials or (b) via subscription through payment
          of a subscription fee or (c) a pay-per-view model with or without
          advertisements/commercials or (d) with a combination of the foregoing
          on the Site.{'\n'} {'\n'} Use of the Services (including access to the
          Content) is subject to compliance with these Terms and any end user
          license agreement that might accompany the applicable Service.
          Therefore, by visiting the TVF Site or using any of the Services
          through any other Access Point you are agreeing to these Terms.
          {'\n'} {'\n'} {'\n'}
        </Text>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'black',
  },
  Header: {
    width: '100%',
    backgroundColor: '#232323',
    flexDirection: 'row',
    alignItems: 'center',
  },
  arrowView: {
    marginTop: vh(12),
    width: vw(20),
    height: vh(10),
    marginLeft: vw(14),
    alignItems: 'center',
    marginBottom: vh(17),
  },
  icon: {
    width: vw(25),
    height: vh(20),
  },
  viewProfile: {
    marginTop: vh(6),
    marginLeft: '10%',
  },
  headerText: {color: 'white', fontSize: normalize(16)},
  subHeader: {
    backgroundColor: 'rgba(255,193,4,0.98)',
    padding: normalize(10),
    paddingHorizontal: vw(29),
    marginTop: vh(40),
    marginBottom: vh(20),
  },
  text: {
    color: 'white',
    fontSize: normalize(25),
  },
});
